// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.5
// source: proto/server_manager/server_manager.proto

package server_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ServerManagerService_ServerInfoGet_FullMethodName = "/server_manager.ServerManagerService/ServerInfoGet"
)

// ServerManagerServiceClient is the client API for ServerManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerManagerServiceClient interface {
	ServerInfoGet(ctx context.Context, in *ServerInfoGetReq, opts ...grpc.CallOption) (*ServerInfoGetResp, error)
}

type serverManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerManagerServiceClient(cc grpc.ClientConnInterface) ServerManagerServiceClient {
	return &serverManagerServiceClient{cc}
}

func (c *serverManagerServiceClient) ServerInfoGet(ctx context.Context, in *ServerInfoGetReq, opts ...grpc.CallOption) (*ServerInfoGetResp, error) {
	out := new(ServerInfoGetResp)
	err := c.cc.Invoke(ctx, ServerManagerService_ServerInfoGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerManagerServiceServer is the server API for ServerManagerService service.
// All implementations must embed UnimplementedServerManagerServiceServer
// for forward compatibility
type ServerManagerServiceServer interface {
	ServerInfoGet(context.Context, *ServerInfoGetReq) (*ServerInfoGetResp, error)
	mustEmbedUnimplementedServerManagerServiceServer()
}

// UnimplementedServerManagerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServerManagerServiceServer struct {
}

func (UnimplementedServerManagerServiceServer) ServerInfoGet(context.Context, *ServerInfoGetReq) (*ServerInfoGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerInfoGet not implemented")
}
func (UnimplementedServerManagerServiceServer) mustEmbedUnimplementedServerManagerServiceServer() {}

// UnsafeServerManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerManagerServiceServer will
// result in compilation errors.
type UnsafeServerManagerServiceServer interface {
	mustEmbedUnimplementedServerManagerServiceServer()
}

func RegisterServerManagerServiceServer(s grpc.ServiceRegistrar, srv ServerManagerServiceServer) {
	s.RegisterService(&ServerManagerService_ServiceDesc, srv)
}

func _ServerManagerService_ServerInfoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfoGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerManagerServiceServer).ServerInfoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerManagerService_ServerInfoGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerManagerServiceServer).ServerInfoGet(ctx, req.(*ServerInfoGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerManagerService_ServiceDesc is the grpc.ServiceDesc for ServerManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_manager.ServerManagerService",
	HandlerType: (*ServerManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerInfoGet",
			Handler:    _ServerManagerService_ServerInfoGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/server_manager/server_manager.proto",
}
