// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.3
// source: proto/promotion/promotion.proto

package promotion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SeckillReq requests an atomic promotion-stock deduction.
type SeckillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromotionId  uint64 `protobuf:"varint,1,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`    // 促销活动 ID
	ProductId    uint64 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`          // 促销产品 ID
	PayNum       int32  `protobuf:"varint,3,opt,name=pay_num,json=payNum,proto3" json:"pay_num,omitempty"`                   // 实际付款数量
	Price        int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`                                   // 价格，使用货币最小单位
	CurrencyType int32  `protobuf:"varint,5,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"` // 货币类型
	RequestId    string `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`           // 贯穿秒杀、订单创建和支付的业务请求 ID
}

func (x *SeckillReq) Reset() {
	*x = SeckillReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_promotion_promotion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeckillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillReq) ProtoMessage() {}

func (x *SeckillReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_promotion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillReq.ProtoReflect.Descriptor instead.
func (*SeckillReq) Descriptor() ([]byte, []int) {
	return file_proto_promotion_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillReq) GetPromotionId() uint64 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

func (x *SeckillReq) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SeckillReq) GetPayNum() int32 {
	if x != nil {
		return x.PayNum
	}
	return 0
}

func (x *SeckillReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeckillReq) GetCurrencyType() int32 {
	if x != nil {
		return x.CurrencyType
	}
	return 0
}

func (x *SeckillReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SeckillResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SeckillResp) Reset() {
	*x = SeckillResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_promotion_promotion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeckillResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResp) ProtoMessage() {}

func (x *SeckillResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_promotion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResp.ProtoReflect.Descriptor instead.
func (*SeckillResp) Descriptor() ([]byte, []int) {
	return file_proto_promotion_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PromotionStockRefreshReq selects promotion products whose valid stock is
// written to Redis. Both fields absent means all currently valid promotions;
// only promotion_id means all valid products in that promotion.
type PromotionStockRefreshReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PromotionId *uint64 `protobuf:"varint,1,opt,name=promotion_id,json=promotionId,proto3,oneof" json:"promotion_id,omitempty"`
	ProductId   *uint64 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
}

func (x *PromotionStockRefreshReq) Reset() {
	*x = PromotionStockRefreshReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_promotion_promotion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromotionStockRefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionStockRefreshReq) ProtoMessage() {}

func (x *PromotionStockRefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_promotion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionStockRefreshReq.ProtoReflect.Descriptor instead.
func (*PromotionStockRefreshReq) Descriptor() ([]byte, []int) {
	return file_proto_promotion_promotion_proto_rawDescGZIP(), []int{2}
}

func (x *PromotionStockRefreshReq) GetPromotionId() uint64 {
	if x != nil && x.PromotionId != nil {
		return *x.PromotionId
	}
	return 0
}

func (x *PromotionStockRefreshReq) GetProductId() uint64 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

type PromotionStockRefreshResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshedCount int32 `protobuf:"varint,1,opt,name=refreshed_count,json=refreshedCount,proto3" json:"refreshed_count,omitempty"`
}

func (x *PromotionStockRefreshResp) Reset() {
	*x = PromotionStockRefreshResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_promotion_promotion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromotionStockRefreshResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionStockRefreshResp) ProtoMessage() {}

func (x *PromotionStockRefreshResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_promotion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionStockRefreshResp.ProtoReflect.Descriptor instead.
func (*PromotionStockRefreshResp) Descriptor() ([]byte, []int) {
	return file_proto_promotion_promotion_proto_rawDescGZIP(), []int{3}
}

func (x *PromotionStockRefreshResp) GetRefreshedCount() int32 {
	if x != nil {
		return x.RefreshedCount
	}
	return 0
}

var File_proto_promotion_promotion_proto protoreflect.FileDescriptor

var file_proto_promotion_promotion_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc1, 0x01, 0x0a,
	0x0a, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x70, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x22, 0x27, 0x0a, 0x0b, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x18, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x22,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x01, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x88,
	0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x22, 0x44, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x27, 0x0a, 0x0f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xb0, 0x01, 0x0a, 0x10, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a,
	0x07, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x63, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x63, 0x6b,
	0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x62, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x42, 0x2d, 0x5a, 0x2b, 0x6f,
	0x6e, 0x65, 0x5f, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x3b, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_promotion_promotion_proto_rawDescOnce sync.Once
	file_proto_promotion_promotion_proto_rawDescData = file_proto_promotion_promotion_proto_rawDesc
)

func file_proto_promotion_promotion_proto_rawDescGZIP() []byte {
	file_proto_promotion_promotion_proto_rawDescOnce.Do(func() {
		file_proto_promotion_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_promotion_promotion_proto_rawDescData)
	})
	return file_proto_promotion_promotion_proto_rawDescData
}

var file_proto_promotion_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_promotion_promotion_proto_goTypes = []interface{}{
	(*SeckillReq)(nil),                // 0: promotion.SeckillReq
	(*SeckillResp)(nil),               // 1: promotion.SeckillResp
	(*PromotionStockRefreshReq)(nil),  // 2: promotion.PromotionStockRefreshReq
	(*PromotionStockRefreshResp)(nil), // 3: promotion.PromotionStockRefreshResp
}
var file_proto_promotion_promotion_proto_depIdxs = []int32{
	0, // 0: promotion.PromotionService.Seckill:input_type -> promotion.SeckillReq
	2, // 1: promotion.PromotionService.PromotionStockRefresh:input_type -> promotion.PromotionStockRefreshReq
	1, // 2: promotion.PromotionService.Seckill:output_type -> promotion.SeckillResp
	3, // 3: promotion.PromotionService.PromotionStockRefresh:output_type -> promotion.PromotionStockRefreshResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_promotion_promotion_proto_init() }
func file_proto_promotion_promotion_proto_init() {
	if File_proto_promotion_promotion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_promotion_promotion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeckillReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_promotion_promotion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeckillResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_promotion_promotion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromotionStockRefreshReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_promotion_promotion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromotionStockRefreshResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_promotion_promotion_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_promotion_promotion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_promotion_promotion_proto_goTypes,
		DependencyIndexes: file_proto_promotion_promotion_proto_depIdxs,
		MessageInfos:      file_proto_promotion_promotion_proto_msgTypes,
	}.Build()
	File_proto_promotion_promotion_proto = out.File
	file_proto_promotion_promotion_proto_rawDesc = nil
	file_proto_promotion_promotion_proto_goTypes = nil
	file_proto_promotion_promotion_proto_depIdxs = nil
}
