// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: proto/promotion/promotion.proto

package promotion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PromotionService_Seckill_FullMethodName               = "/promotion.PromotionService/Seckill"
	PromotionService_PromotionStockRefresh_FullMethodName = "/promotion.PromotionService/PromotionStockRefresh"
)

// PromotionServiceClient is the client API for PromotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromotionServiceClient interface {
	// Seckill gets the user identity from RPC context, atomically
	// validates limits and deducts stock, then publishes the result to the
	// promotion_order_create Kafka topic.
	Seckill(ctx context.Context, in *SeckillReq, opts ...grpc.CallOption) (*SeckillResp, error)
	// PromotionStockRefresh writes valid promotion-product stock to Redis under
	// promotion:{promotion_id}:{product_id}.
	PromotionStockRefresh(ctx context.Context, in *PromotionStockRefreshReq, opts ...grpc.CallOption) (*PromotionStockRefreshResp, error)
}

type promotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionServiceClient(cc grpc.ClientConnInterface) PromotionServiceClient {
	return &promotionServiceClient{cc}
}

func (c *promotionServiceClient) Seckill(ctx context.Context, in *SeckillReq, opts ...grpc.CallOption) (*SeckillResp, error) {
	out := new(SeckillResp)
	err := c.cc.Invoke(ctx, PromotionService_Seckill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) PromotionStockRefresh(ctx context.Context, in *PromotionStockRefreshReq, opts ...grpc.CallOption) (*PromotionStockRefreshResp, error) {
	out := new(PromotionStockRefreshResp)
	err := c.cc.Invoke(ctx, PromotionService_PromotionStockRefresh_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServiceServer is the server API for PromotionService service.
// All implementations must embed UnimplementedPromotionServiceServer
// for forward compatibility
type PromotionServiceServer interface {
	// Seckill gets the user identity from RPC context, atomically
	// validates limits and deducts stock, then publishes the result to the
	// promotion_order_create Kafka topic.
	Seckill(context.Context, *SeckillReq) (*SeckillResp, error)
	// PromotionStockRefresh writes valid promotion-product stock to Redis under
	// promotion:{promotion_id}:{product_id}.
	PromotionStockRefresh(context.Context, *PromotionStockRefreshReq) (*PromotionStockRefreshResp, error)
	mustEmbedUnimplementedPromotionServiceServer()
}

// UnimplementedPromotionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPromotionServiceServer struct {
}

func (UnimplementedPromotionServiceServer) Seckill(context.Context, *SeckillReq) (*SeckillResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Seckill not implemented")
}
func (UnimplementedPromotionServiceServer) PromotionStockRefresh(context.Context, *PromotionStockRefreshReq) (*PromotionStockRefreshResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromotionStockRefresh not implemented")
}
func (UnimplementedPromotionServiceServer) mustEmbedUnimplementedPromotionServiceServer() {}

// UnsafePromotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionServiceServer will
// result in compilation errors.
type UnsafePromotionServiceServer interface {
	mustEmbedUnimplementedPromotionServiceServer()
}

func RegisterPromotionServiceServer(s grpc.ServiceRegistrar, srv PromotionServiceServer) {
	s.RegisterService(&PromotionService_ServiceDesc, srv)
}

func _PromotionService_Seckill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeckillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).Seckill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_Seckill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).Seckill(ctx, req.(*SeckillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_PromotionStockRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromotionStockRefreshReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).PromotionStockRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_PromotionStockRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).PromotionStockRefresh(ctx, req.(*PromotionStockRefreshReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PromotionService_ServiceDesc is the grpc.ServiceDesc for PromotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promotion.PromotionService",
	HandlerType: (*PromotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Seckill",
			Handler:    _PromotionService_Seckill_Handler,
		},
		{
			MethodName: "PromotionStockRefresh",
			Handler:    _PromotionService_PromotionStockRefresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/promotion/promotion.proto",
}
