// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"promotion/internal/dao/internal"
)

// promotionInventoryDao is the data access object for the table promotion_inventory.
// You can define custom methods on it to extend its functionality as needed.
type promotionInventoryDao struct {
	*internal.PromotionInventoryDao
}

var (
	// PromotionInventory is a globally accessible object for table promotion_inventory operations.
	PromotionInventory = promotionInventoryDao{internal.NewPromotionInventoryDao()}
)

// Add your custom methods and functionality below.
