// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"promotion/internal/dao/internal"
)

// promotionDao is the data access object for the table promotion.
// You can define custom methods on it to extend its functionality as needed.
type promotionDao struct {
	*internal.PromotionDao
}

var (
	// Promotion is a globally accessible object for table promotion operations.
	Promotion = promotionDao{internal.NewPromotionDao()}
)

// Add your custom methods and functionality below.
