// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"promotion/internal/dao/internal"
)

// promotionProductDao is the data access object for the table promotion_product.
// You can define custom methods on it to extend its functionality as needed.
type promotionProductDao struct {
	*internal.PromotionProductDao
}

var (
	// PromotionProduct is a globally accessible object for table promotion_product operations.
	PromotionProduct = promotionProductDao{internal.NewPromotionProductDao()}
)

// Add your custom methods and functionality below.
