// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.3
// source: proto/computing/computing.proto

package computing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollisionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShapeType   string  `protobuf:"bytes,1,opt,name=shape_type,json=shapeType,proto3" json:"shape_type,omitempty"` //形状
	X           float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y           float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Radius      float64 `protobuf:"fixed64,4,opt,name=radius,proto3" json:"radius,omitempty"` //半径
	Width       float64 `protobuf:"fixed64,5,opt,name=width,proto3" json:"width,omitempty"`
	Height      float64 `protobuf:"fixed64,6,opt,name=height,proto3" json:"height,omitempty"`
	Rotation    float64 `protobuf:"fixed64,7,opt,name=rotation,proto3" json:"rotation,omitempty"`                        //旋转角度
	CollisionId string  `protobuf:"bytes,8,opt,name=collision_id,json=collisionId,proto3" json:"collision_id,omitempty"` //碰撞id
}

func (x *CollisionInfo) Reset() {
	*x = CollisionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computing_computing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollisionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollisionInfo) ProtoMessage() {}

func (x *CollisionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computing_computing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollisionInfo.ProtoReflect.Descriptor instead.
func (*CollisionInfo) Descriptor() ([]byte, []int) {
	return file_proto_computing_computing_proto_rawDescGZIP(), []int{0}
}

func (x *CollisionInfo) GetShapeType() string {
	if x != nil {
		return x.ShapeType
	}
	return ""
}

func (x *CollisionInfo) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CollisionInfo) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CollisionInfo) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *CollisionInfo) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CollisionInfo) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CollisionInfo) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *CollisionInfo) GetCollisionId() string {
	if x != nil {
		return x.CollisionId
	}
	return ""
}

type CollisionCalculationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstCollision  []*CollisionInfo `protobuf:"bytes,1,rep,name=first_collision,json=firstCollision,proto3" json:"first_collision,omitempty"`
	SecondCollision []*CollisionInfo `protobuf:"bytes,2,rep,name=second_collision,json=secondCollision,proto3" json:"second_collision,omitempty"`
}

func (x *CollisionCalculationReq) Reset() {
	*x = CollisionCalculationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computing_computing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollisionCalculationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollisionCalculationReq) ProtoMessage() {}

func (x *CollisionCalculationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computing_computing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollisionCalculationReq.ProtoReflect.Descriptor instead.
func (*CollisionCalculationReq) Descriptor() ([]byte, []int) {
	return file_proto_computing_computing_proto_rawDescGZIP(), []int{1}
}

func (x *CollisionCalculationReq) GetFirstCollision() []*CollisionInfo {
	if x != nil {
		return x.FirstCollision
	}
	return nil
}

func (x *CollisionCalculationReq) GetSecondCollision() []*CollisionInfo {
	if x != nil {
		return x.SecondCollision
	}
	return nil
}

type CollisionCalculationResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsContact bool `protobuf:"varint,1,opt,name=is_contact,json=isContact,proto3" json:"is_contact,omitempty"`
}

func (x *CollisionCalculationResp) Reset() {
	*x = CollisionCalculationResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_computing_computing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollisionCalculationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollisionCalculationResp) ProtoMessage() {}

func (x *CollisionCalculationResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_computing_computing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollisionCalculationResp.ProtoReflect.Descriptor instead.
func (*CollisionCalculationResp) Descriptor() ([]byte, []int) {
	return file_proto_computing_computing_proto_rawDescGZIP(), []int{2}
}

func (x *CollisionCalculationResp) GetIsContact() bool {
	if x != nil {
		return x.IsContact
	}
	return false
}

var File_proto_computing_computing_proto protoreflect.FileDescriptor

var file_proto_computing_computing_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e,
	0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xcf, 0x01, 0x0a,
	0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x68, 0x61, 0x70, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x61, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64,
	0x69, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xa1,
	0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x41, 0x0a, 0x0f, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a,
	0x10, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x18, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x32, 0x73, 0x0a,
	0x10, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5f, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x2d, 0x5a, 0x2b, 0x6f, 0x6e, 0x65, 0x5f, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74,
	0x75, 0x72, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x3b, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_computing_computing_proto_rawDescOnce sync.Once
	file_proto_computing_computing_proto_rawDescData = file_proto_computing_computing_proto_rawDesc
)

func file_proto_computing_computing_proto_rawDescGZIP() []byte {
	file_proto_computing_computing_proto_rawDescOnce.Do(func() {
		file_proto_computing_computing_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_computing_computing_proto_rawDescData)
	})
	return file_proto_computing_computing_proto_rawDescData
}

var file_proto_computing_computing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_computing_computing_proto_goTypes = []interface{}{
	(*CollisionInfo)(nil),            // 0: computing.CollisionInfo
	(*CollisionCalculationReq)(nil),  // 1: computing.CollisionCalculationReq
	(*CollisionCalculationResp)(nil), // 2: computing.CollisionCalculationResp
}
var file_proto_computing_computing_proto_depIdxs = []int32{
	0, // 0: computing.CollisionCalculationReq.first_collision:type_name -> computing.CollisionInfo
	0, // 1: computing.CollisionCalculationReq.second_collision:type_name -> computing.CollisionInfo
	1, // 2: computing.ComputingService.CollisionCalculation:input_type -> computing.CollisionCalculationReq
	2, // 3: computing.ComputingService.CollisionCalculation:output_type -> computing.CollisionCalculationResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_computing_computing_proto_init() }
func file_proto_computing_computing_proto_init() {
	if File_proto_computing_computing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_computing_computing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollisionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computing_computing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollisionCalculationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_computing_computing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollisionCalculationResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_computing_computing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_computing_computing_proto_goTypes,
		DependencyIndexes: file_proto_computing_computing_proto_depIdxs,
		MessageInfos:      file_proto_computing_computing_proto_msgTypes,
	}.Build()
	File_proto_computing_computing_proto = out.File
	file_proto_computing_computing_proto_rawDesc = nil
	file_proto_computing_computing_proto_goTypes = nil
	file_proto_computing_computing_proto_depIdxs = nil
}
