// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: proto/computing/computing.proto

package computing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ComputingService_CollisionCalculation_FullMethodName = "/computing.ComputingService/CollisionCalculation"
)

// ComputingServiceClient is the client API for ComputingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputingServiceClient interface {
	CollisionCalculation(ctx context.Context, in *CollisionCalculationReq, opts ...grpc.CallOption) (*CollisionCalculationResp, error)
}

type computingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComputingServiceClient(cc grpc.ClientConnInterface) ComputingServiceClient {
	return &computingServiceClient{cc}
}

func (c *computingServiceClient) CollisionCalculation(ctx context.Context, in *CollisionCalculationReq, opts ...grpc.CallOption) (*CollisionCalculationResp, error) {
	out := new(CollisionCalculationResp)
	err := c.cc.Invoke(ctx, ComputingService_CollisionCalculation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputingServiceServer is the server API for ComputingService service.
// All implementations must embed UnimplementedComputingServiceServer
// for forward compatibility
type ComputingServiceServer interface {
	CollisionCalculation(context.Context, *CollisionCalculationReq) (*CollisionCalculationResp, error)
	mustEmbedUnimplementedComputingServiceServer()
}

// UnimplementedComputingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedComputingServiceServer struct {
}

func (UnimplementedComputingServiceServer) CollisionCalculation(context.Context, *CollisionCalculationReq) (*CollisionCalculationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollisionCalculation not implemented")
}
func (UnimplementedComputingServiceServer) mustEmbedUnimplementedComputingServiceServer() {}

// UnsafeComputingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputingServiceServer will
// result in compilation errors.
type UnsafeComputingServiceServer interface {
	mustEmbedUnimplementedComputingServiceServer()
}

func RegisterComputingServiceServer(s grpc.ServiceRegistrar, srv ComputingServiceServer) {
	s.RegisterService(&ComputingService_ServiceDesc, srv)
}

func _ComputingService_CollisionCalculation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollisionCalculationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputingServiceServer).CollisionCalculation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputingService_CollisionCalculation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputingServiceServer).CollisionCalculation(ctx, req.(*CollisionCalculationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputingService_ServiceDesc is the grpc.ServiceDesc for ComputingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "computing.ComputingService",
	HandlerType: (*ComputingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollisionCalculation",
			Handler:    _ComputingService_CollisionCalculation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/computing/computing.proto",
}
