// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"item/internal/dao/internal"
)

// inventoryItemDao is the data access object for the table inventory_item.
// You can define custom methods on it to extend its functionality as needed.
type inventoryItemDao struct {
	*internal.InventoryItemDao
}

var (
	// InventoryItem is a globally accessible object for table inventory_item operations.
	InventoryItem = inventoryItemDao{internal.NewInventoryItemDao()}
)

// Add your custom methods and functionality below.
