// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"item/internal/dao/internal"
)

// inventoryConfDao is the data access object for the table inventory_conf.
// You can define custom methods on it to extend its functionality as needed.
type inventoryConfDao struct {
	*internal.InventoryConfDao
}

var (
	// InventoryConf is a globally accessible object for table inventory_conf operations.
	InventoryConf = inventoryConfDao{internal.NewInventoryConfDao()}
)

// Add your custom methods and functionality below.
