// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"item/internal/dao/internal"
)

// itemInstanceDao is the data access object for the table item_instance.
// You can define custom methods on it to extend its functionality as needed.
type itemInstanceDao struct {
	*internal.ItemInstanceDao
}

var (
	// ItemInstance is a globally accessible object for table item_instance operations.
	ItemInstance = itemInstanceDao{internal.NewItemInstanceDao()}
)

// Add your custom methods and functionality below.
