// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"item/internal/dao/internal"
)

// itemInfoDao is the data access object for the table item_info.
// You can define custom methods on it to extend its functionality as needed.
type itemInfoDao struct {
	*internal.ItemInfoDao
}

var (
	// ItemInfo is a globally accessible object for table item_info operations.
	ItemInfo = itemInfoDao{internal.NewItemInfoDao()}
)

// Add your custom methods and functionality below.
