// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"item/internal/dao/internal"
)

// itemTemplateDao is the data access object for the table item_template.
// You can define custom methods on it to extend its functionality as needed.
type itemTemplateDao struct {
	*internal.ItemTemplateDao
}

var (
	// ItemTemplate is a globally accessible object for table item_template operations.
	ItemTemplate = itemTemplateDao{internal.NewItemTemplateDao()}
)

// Add your custom methods and functionality below.
