
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:zxc563221659@tcp(127.0.0.1:3306)/one_adventure_commerce"
        tables: "promotion,promotion_product,promotion_inventory"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
