// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_manager/internal/dao/internal"
)

// channelInfoDao is the data access object for the table channel_info.
// You can define custom methods on it to extend its functionality as needed.
type channelInfoDao struct {
	*internal.ChannelInfoDao
}

var (
	// ChannelInfo is a globally accessible object for table channel_info operations.
	ChannelInfo = channelInfoDao{internal.NewChannelInfoDao()}
)

// Add your custom methods and functionality below.
