// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"server_manager/internal/dao/internal"
)

// serverInfoDao is the data access object for the table server_info.
// You can define custom methods on it to extend its functionality as needed.
type serverInfoDao struct {
	*internal.ServerInfoDao
}

var (
	// ServerInfo is a globally accessible object for table server_info operations.
	ServerInfo = serverInfoDao{internal.NewServerInfoDao()}
)

// Add your custom methods and functionality below.
