port: 9003
envoyAddress: "127.0.0.1:15001"
etcd:
  endpoints: ["127.0.0.1:2379"]
  dialTimeout: "5s"
  leaseTtl: 10
  serverName: "item"
  instanceId: ""
  address: "host.docker.internal"
  httpPort: 8905
