// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"pay/internal/dao/internal"
)

// paymentTransactionDao is the data access object for the table payment_transaction.
// You can define custom methods on it to extend its functionality as needed.
type paymentTransactionDao struct {
	*internal.PaymentTransactionDao
}

var (
	// PaymentTransaction is a globally accessible object for table payment_transaction operations.
	PaymentTransaction = paymentTransactionDao{internal.NewPaymentTransactionDao()}
)

// Add your custom methods and functionality below.
