// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"pay/internal/dao/internal"
)

// paymentRefundDao is the data access object for the table payment_refund.
// You can define custom methods on it to extend its functionality as needed.
type paymentRefundDao struct {
	*internal.PaymentRefundDao
}

var (
	// PaymentRefund is a globally accessible object for table payment_refund operations.
	PaymentRefund = paymentRefundDao{internal.NewPaymentRefundDao()}
)

// Add your custom methods and functionality below.
