// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"pay/internal/dao/internal"
)

// paymentOrderDao is the data access object for the table payment_order.
// You can define custom methods on it to extend its functionality as needed.
type paymentOrderDao struct {
	*internal.PaymentOrderDao
}

var (
	// PaymentOrder is a globally accessible object for table payment_order operations.
	PaymentOrder = paymentOrderDao{internal.NewPaymentOrderDao()}
)

// Add your custom methods and functionality below.
