server:
  address: ":8903"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
logger:
  level: "all"
  stdout: true
database:
  default:
    link: "mysql:root:12345678@tcp(host.docker.internal:3306)/test"
