#!/usr/bin/env bash

# Clear Redis data generated by the promotion/seckill subsystem.
# Usage: script/clear-promotion-redis.sh [--yes] [pattern]
set -euo pipefail

host="${REDIS_HOST:-127.0.0.1}"
port="${REDIS_PORT:-6379}"
password="${REDIS_PASSWORD:-123456}"
pattern="promotion:*"
confirm=false

usage() {
    echo "Usage: $0 [--yes] [pattern]"
    echo "Default pattern: promotion:*"
    echo "Environment: REDIS_HOST, REDIS_PORT, REDIS_PASSWORD"
    echo "Without --yes, only lists matching keys (dry run)."
}

for arg in "$@"; do
    case "$arg" in
        --yes) confirm=true ;;
        -h|--help) usage; exit 0 ;;
        --*) echo "error: unknown option '$arg'" >&2; usage >&2; exit 2 ;;
        *) pattern="$arg" ;;
    esac
done

command -v redis-cli >/dev/null 2>&1 || {
    echo "error: redis-cli is required" >&2
    exit 127
}

redis_args=(--no-auth-warning -h "$host" -p "$port")
if [[ -n "$password" ]]; then
    redis_args+=(-a "$password")
fi

mapfile -t keys < <(redis-cli "${redis_args[@]}" --scan --pattern "$pattern")
echo "Redis: ${host}:${port}"
echo "Pattern: ${pattern}"
echo "Matched keys: ${#keys[@]}"

if ((${#keys[@]} == 0)); then
    exit 0
fi

printf '%s\n' "${keys[@]}"
if [[ "$confirm" != true ]]; then
    echo "Dry run only. Add --yes to delete these keys."
    exit 0
fi

redis-cli "${redis_args[@]}" --raw DEL "${keys[@]}" >/dev/null
echo "Deleted ${#keys[@]} key(s)."
