#!/usr/bin/env bash
set -uo pipefail

usage() {
    echo "Usage: script/export-schema.sh [-o FILE] [-h HOST] [-P PORT] [-u USER] [-p PASSWORD] [--socket PATH]"
}

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
project_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
output="$project_dir/schema-$(date +%Y%m%d-%H%M%S).sql"
host="127.0.0.1"
port="3306"
user="root"
password="${MYSQL_PWD:-zxc563221659}"
socket=""

while (($#)); do
    case "$1" in
        -o|--output) [[ $# -ge 2 ]] || exit 2; output=$2; shift 2 ;;
        -h|--host) [[ $# -ge 2 ]] || exit 2; host=$2; shift 2 ;;
        -P|--port) [[ $# -ge 2 ]] || exit 2; port=$2; shift 2 ;;
        -u|--user) [[ $# -ge 2 ]] || exit 2; user=$2; shift 2 ;;
        -p|--password) [[ $# -ge 2 ]] || exit 2; password=$2; shift 2 ;;
        --socket) [[ $# -ge 2 ]] || exit 2; socket=$2; shift 2 ;;
        --help) usage; exit 0 ;;
        *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
done

command -v mysql >/dev/null 2>&1 || { echo "mysql client is required" >&2; exit 127; }
mkdir -p "$(dirname -- "$output")" || exit 1
tmp_output=$(mktemp "${TMPDIR:-/tmp}/one-adventure-schema.XXXXXX")
trap 'rm -f "$tmp_output"' EXIT

# This deterministic list mirrors the GoFrame DAO configs in */hack/config.yaml.
databases=(
    "one_adventure_commerce|orders promotion promotion_product promotion_inventory payment_order payment_transaction payment_refund"
    "one_adventure_user|user"
    "one_adventure_item|item_info item_instance item_template inventory_item inventory_conf"
    "one_adventure_server|server_info channel_info"
)

mysql_args=(--batch --skip-column-names --protocol=tcp --host="$host" --port="$port" --user="$user")
if [[ -n "$socket" ]]; then
    mysql_args=(--batch --skip-column-names --protocol=socket --socket="$socket" --user="$user")
fi

{
    printf -- '-- Generated by %s on %s\n\n' "$(basename "$0")" "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf 'SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n'
} >"$tmp_output"

failed=0
for definition in "${databases[@]}"; do
    database=${definition%%|*}
    table_list=${definition#*|}
    printf -- '-- Database: %s\nCREATE DATABASE IF NOT EXISTS `%s`;\nUSE `%s`;\n\n' "$database" "$database" "$database" >>"$tmp_output"
    for table in $table_list; do
        create_sql=$(MYSQL_PWD="$password" mysql "${mysql_args[@]}" "$database" -e "SHOW CREATE TABLE \`$table\`;" 2>&1)
        if (($? != 0)); then
            printf -- '-- ERROR: failed to export `%s`.`%s`: %s\n' "$database" "$table" "$create_sql" >>"$tmp_output"
            echo "failed: $database.$table" >&2
            failed=1
            continue
        fi
        create_statement=${create_sql#*$'\t'}
        if [[ "$create_statement" == "$create_sql" || -z "$create_statement" ]]; then
            printf -- '-- ERROR: empty CREATE TABLE result for `%s`.`%s`\n' "$database" "$table" >>"$tmp_output"
            failed=1
            continue
        fi
        printf '%s;\n\n' "$create_statement" >>"$tmp_output"
        echo "exported: $database.$table"
    done
done

printf 'SET FOREIGN_KEY_CHECKS=1;\n' >>"$tmp_output"
mv "$tmp_output" "$output" || exit 1
echo "schema written to: $output"
exit "$failed"
