syntax = "proto3";

package ws_gateway;

option go_package = "one_adventure_rpc/proto/ws_gateway;ws_gateway";

message ServerInfoGetReq{
  int32 type=1; //0 全部可用逻辑服务器 1未被扮演的逻辑服务器 2已扮演的逻辑服务器
}


message ChannelInfo{
  uint64 id=1;
  int32 index=2;
  string name=3;
  uint64 server_id=4;
  int64 ws_connections=5;
}

message ServerInfo{
  uint64  id=1;
  string name=2;
  repeated ChannelInfo channels=3;
  bool occupied=4;
  string instance_id=5;
  string address=6;
  int32 ws_port=7;
  int64 ws_connections=8;
  bool online=9;

}

message ServerInfoGetResp{
  repeated ServerInfo servers=1;
}

message ChannelInfoGetReq { uint64 server_id = 1; }
message ChannelInfoGetResp { repeated ChannelInfo channels = 1; }

// 定义服务接口
service WsGatewayService {
  rpc ServerInfoGet(ServerInfoGetReq) returns (ServerInfoGetResp);
  rpc ChannelInfoGet(ChannelInfoGetReq) returns (ChannelInfoGetResp);
}
