// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.3
// source: proto/ws_gateway/ws_gateway.proto

package ws_gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerInfoGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` //0 全部可用逻辑服务器 1未被扮演的逻辑服务器 2已扮演的逻辑服务器
}

func (x *ServerInfoGetReq) Reset() {
	*x = ServerInfoGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoGetReq) ProtoMessage() {}

func (x *ServerInfoGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoGetReq.ProtoReflect.Descriptor instead.
func (*ServerInfoGetReq) Descriptor() ([]byte, []int) {
	return file_proto_ws_gateway_ws_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfoGetReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ChannelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         int32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ServerId      uint64 `protobuf:"varint,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	WsConnections int64  `protobuf:"varint,5,opt,name=ws_connections,json=wsConnections,proto3" json:"ws_connections,omitempty"`
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_proto_ws_gateway_ws_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChannelInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChannelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelInfo) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ChannelInfo) GetWsConnections() int64 {
	if x != nil {
		return x.WsConnections
	}
	return 0
}

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Channels      []*ChannelInfo `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	Occupied      bool           `protobuf:"varint,4,opt,name=occupied,proto3" json:"occupied,omitempty"`
	InstanceId    string         `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Address       string         `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	WsPort        int32          `protobuf:"varint,7,opt,name=ws_port,json=wsPort,proto3" json:"ws_port,omitempty"`
	WsConnections int64          `protobuf:"varint,8,opt,name=ws_connections,json=wsConnections,proto3" json:"ws_connections,omitempty"`
	Online        bool           `protobuf:"varint,9,opt,name=online,proto3" json:"online,omitempty"`
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_proto_ws_gateway_ws_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ServerInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetChannels() []*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ServerInfo) GetOccupied() bool {
	if x != nil {
		return x.Occupied
	}
	return false
}

func (x *ServerInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ServerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerInfo) GetWsPort() int32 {
	if x != nil {
		return x.WsPort
	}
	return 0
}

func (x *ServerInfo) GetWsConnections() int64 {
	if x != nil {
		return x.WsConnections
	}
	return 0
}

func (x *ServerInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type ServerInfoGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []*ServerInfo `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *ServerInfoGetResp) Reset() {
	*x = ServerInfoGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoGetResp) ProtoMessage() {}

func (x *ServerInfoGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoGetResp.ProtoReflect.Descriptor instead.
func (*ServerInfoGetResp) Descriptor() ([]byte, []int) {
	return file_proto_ws_gateway_ws_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfoGetResp) GetServers() []*ServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ChannelInfoGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint64 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *ChannelInfoGetReq) Reset() {
	*x = ChannelInfoGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelInfoGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfoGetReq) ProtoMessage() {}

func (x *ChannelInfoGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfoGetReq.ProtoReflect.Descriptor instead.
func (*ChannelInfoGetReq) Descriptor() ([]byte, []int) {
	return file_proto_ws_gateway_ws_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelInfoGetReq) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type ChannelInfoGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*ChannelInfo `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
}

func (x *ChannelInfoGetResp) Reset() {
	*x = ChannelInfoGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelInfoGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfoGetResp) ProtoMessage() {}

func (x *ChannelInfoGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_gateway_ws_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfoGetResp.ProtoReflect.Descriptor instead.
func (*ChannelInfoGetResp) Descriptor() ([]byte, []int) {
	return file_proto_ws_gateway_ws_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelInfoGetResp) GetChannels() []*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_proto_ws_gateway_ws_gateway_proto protoreflect.FileDescriptor

var file_proto_ws_gateway_ws_gateway_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2f, 0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22,
	0x26, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x0e, 0x77, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x77, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x94, 0x02, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77, 0x73, 0x5f,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x73, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x77, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x77, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x45, 0x0a, 0x11,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x30, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x22, 0x30, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x08, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x32, 0xb1, 0x01, 0x0a, 0x10, 0x57, 0x73, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4f, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x47, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x2f, 0x5a, 0x2d, 0x6f, 0x6e, 0x65, 0x5f, 0x61, 0x64, 0x76, 0x65,
	0x6e, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x77, 0x73, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x3b, 0x77, 0x73, 0x5f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ws_gateway_ws_gateway_proto_rawDescOnce sync.Once
	file_proto_ws_gateway_ws_gateway_proto_rawDescData = file_proto_ws_gateway_ws_gateway_proto_rawDesc
)

func file_proto_ws_gateway_ws_gateway_proto_rawDescGZIP() []byte {
	file_proto_ws_gateway_ws_gateway_proto_rawDescOnce.Do(func() {
		file_proto_ws_gateway_ws_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ws_gateway_ws_gateway_proto_rawDescData)
	})
	return file_proto_ws_gateway_ws_gateway_proto_rawDescData
}

var file_proto_ws_gateway_ws_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ws_gateway_ws_gateway_proto_goTypes = []interface{}{
	(*ServerInfoGetReq)(nil),   // 0: ws_gateway.ServerInfoGetReq
	(*ChannelInfo)(nil),        // 1: ws_gateway.ChannelInfo
	(*ServerInfo)(nil),         // 2: ws_gateway.ServerInfo
	(*ServerInfoGetResp)(nil),  // 3: ws_gateway.ServerInfoGetResp
	(*ChannelInfoGetReq)(nil),  // 4: ws_gateway.ChannelInfoGetReq
	(*ChannelInfoGetResp)(nil), // 5: ws_gateway.ChannelInfoGetResp
}
var file_proto_ws_gateway_ws_gateway_proto_depIdxs = []int32{
	1, // 0: ws_gateway.ServerInfo.channels:type_name -> ws_gateway.ChannelInfo
	2, // 1: ws_gateway.ServerInfoGetResp.servers:type_name -> ws_gateway.ServerInfo
	1, // 2: ws_gateway.ChannelInfoGetResp.channels:type_name -> ws_gateway.ChannelInfo
	0, // 3: ws_gateway.WsGatewayService.ServerInfoGet:input_type -> ws_gateway.ServerInfoGetReq
	4, // 4: ws_gateway.WsGatewayService.ChannelInfoGet:input_type -> ws_gateway.ChannelInfoGetReq
	3, // 5: ws_gateway.WsGatewayService.ServerInfoGet:output_type -> ws_gateway.ServerInfoGetResp
	5, // 6: ws_gateway.WsGatewayService.ChannelInfoGet:output_type -> ws_gateway.ChannelInfoGetResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ws_gateway_ws_gateway_proto_init() }
func file_proto_ws_gateway_ws_gateway_proto_init() {
	if File_proto_ws_gateway_ws_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ws_gateway_ws_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ws_gateway_ws_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ws_gateway_ws_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ws_gateway_ws_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ws_gateway_ws_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelInfoGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ws_gateway_ws_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelInfoGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ws_gateway_ws_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ws_gateway_ws_gateway_proto_goTypes,
		DependencyIndexes: file_proto_ws_gateway_ws_gateway_proto_depIdxs,
		MessageInfos:      file_proto_ws_gateway_ws_gateway_proto_msgTypes,
	}.Build()
	File_proto_ws_gateway_ws_gateway_proto = out.File
	file_proto_ws_gateway_ws_gateway_proto_rawDesc = nil
	file_proto_ws_gateway_ws_gateway_proto_goTypes = nil
	file_proto_ws_gateway_ws_gateway_proto_depIdxs = nil
}
