// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: proto/ws_gateway/ws_gateway.proto

package ws_gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WsGatewayService_ServerInfoGet_FullMethodName  = "/ws_gateway.WsGatewayService/ServerInfoGet"
	WsGatewayService_ChannelInfoGet_FullMethodName = "/ws_gateway.WsGatewayService/ChannelInfoGet"
)

// WsGatewayServiceClient is the client API for WsGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WsGatewayServiceClient interface {
	ServerInfoGet(ctx context.Context, in *ServerInfoGetReq, opts ...grpc.CallOption) (*ServerInfoGetResp, error)
	ChannelInfoGet(ctx context.Context, in *ChannelInfoGetReq, opts ...grpc.CallOption) (*ChannelInfoGetResp, error)
}

type wsGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWsGatewayServiceClient(cc grpc.ClientConnInterface) WsGatewayServiceClient {
	return &wsGatewayServiceClient{cc}
}

func (c *wsGatewayServiceClient) ServerInfoGet(ctx context.Context, in *ServerInfoGetReq, opts ...grpc.CallOption) (*ServerInfoGetResp, error) {
	out := new(ServerInfoGetResp)
	err := c.cc.Invoke(ctx, WsGatewayService_ServerInfoGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wsGatewayServiceClient) ChannelInfoGet(ctx context.Context, in *ChannelInfoGetReq, opts ...grpc.CallOption) (*ChannelInfoGetResp, error) {
	out := new(ChannelInfoGetResp)
	err := c.cc.Invoke(ctx, WsGatewayService_ChannelInfoGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WsGatewayServiceServer is the server API for WsGatewayService service.
// All implementations must embed UnimplementedWsGatewayServiceServer
// for forward compatibility
type WsGatewayServiceServer interface {
	ServerInfoGet(context.Context, *ServerInfoGetReq) (*ServerInfoGetResp, error)
	ChannelInfoGet(context.Context, *ChannelInfoGetReq) (*ChannelInfoGetResp, error)
	mustEmbedUnimplementedWsGatewayServiceServer()
}

// UnimplementedWsGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWsGatewayServiceServer struct {
}

func (UnimplementedWsGatewayServiceServer) ServerInfoGet(context.Context, *ServerInfoGetReq) (*ServerInfoGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerInfoGet not implemented")
}
func (UnimplementedWsGatewayServiceServer) ChannelInfoGet(context.Context, *ChannelInfoGetReq) (*ChannelInfoGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChannelInfoGet not implemented")
}
func (UnimplementedWsGatewayServiceServer) mustEmbedUnimplementedWsGatewayServiceServer() {}

// UnsafeWsGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WsGatewayServiceServer will
// result in compilation errors.
type UnsafeWsGatewayServiceServer interface {
	mustEmbedUnimplementedWsGatewayServiceServer()
}

func RegisterWsGatewayServiceServer(s grpc.ServiceRegistrar, srv WsGatewayServiceServer) {
	s.RegisterService(&WsGatewayService_ServiceDesc, srv)
}

func _WsGatewayService_ServerInfoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfoGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsGatewayServiceServer).ServerInfoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsGatewayService_ServerInfoGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsGatewayServiceServer).ServerInfoGet(ctx, req.(*ServerInfoGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WsGatewayService_ChannelInfoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelInfoGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsGatewayServiceServer).ChannelInfoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsGatewayService_ChannelInfoGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsGatewayServiceServer).ChannelInfoGet(ctx, req.(*ChannelInfoGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WsGatewayService_ServiceDesc is the grpc.ServiceDesc for WsGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WsGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ws_gateway.WsGatewayService",
	HandlerType: (*WsGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerInfoGet",
			Handler:    _WsGatewayService_ServerInfoGet_Handler,
		},
		{
			MethodName: "ChannelInfoGet",
			Handler:    _WsGatewayService_ChannelInfoGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ws_gateway/ws_gateway.proto",
}
