syntax = "proto3";

package pay;

option go_package = "one_adventure_rpc/proto/pay;pay";

service PayService {
  rpc CreatePayment(CreatePaymentReq) returns (TransactionResp);
  rpc CreateTransaction(CreateTransactionReq) returns (TransactionResp);
  rpc CancelTransaction(CancelTransactionReq) returns (TransactionResp);
  rpc ThirdPartyCallback(ThirdPartyCallbackReq) returns (TransactionResp);
}

message CreatePaymentReq {
  string request_id = 1;
  string order_no = 2;
  string channel = 3;
  string currency = 4;
}

message CreateTransactionReq {
  string request_id = 1;
  string order_no = 2;
  uint64 user_id = 3;
  int64 amount = 4;
  string currency = 5;
  string channel = 6;
}

message CancelTransactionReq {
  string transaction_no = 1;
  string request_id = 2;
  string reason = 3;
}

message ThirdPartyCallbackReq {
  string transaction_no = 1;
  string third_party_transaction_no = 2;
  string status = 3;
  string raw_data = 4;
}

message TransactionResp {
  bool success = 1;
  string payment_no = 2;
  string transaction_no = 3;
  string status = 4;
}
