server: {address: ":8000", openapiPath: "/api.json", swaggerPath: "/swagger"}
logger: {level: "all", stdout: true}
database:
  default: {link: "mysql:root:zxc563221659@tcp(host.docker.internal:3306)/one_adventure_commerce"}
redis:
  default: {address: "host.docker.internal:6379", pass: "123456"}
